### ISSUE TITLE
Make all AMPEL dependencies public

### ISSUE THREAD

**Issue by simeonreusch** [desy-multimessenger/ampel_followup_pipeline#2]
**Is your feature request related to a problem? Please describe.**
Will make install much easier

**Describe the solution you'd like**
All AMPEL-packages that ampel_followup_pipeline depends on should be publicly available on pypi.org

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by robertdstein** [comment]
As a consequence, you could then make the pipeline itself available on pypi.

**Comment by robertdstein** [comment]
related comment to #5 , `ampel-contrib-ztfbh` might be a bottleneck

**Comment by robertdstein** [comment]
whenever this is done, we should eliminate `ampel_requirements.txt` entirely and put it all in `requirements.txt`

**Comment by robertdstein** [comment]
As of https://github.com/desy-multimessenger/ampel_followup_pipeline/commit/4cb9907cc82a5354ec793bfdf2e828c9bc2fcd51 this is done!
